---
# markdownlint configuration: default built-in rules plus custom rule overrides

default: true

# MD013/line-length - line length limits (non-default)
MD013:
  line_length: 500
  heading_line_length: 500
  code_block_line_length: 500
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false

# MD033/no-inline-html - allow anchor elements for custom anchors
MD033:
  allowed_elements: ["a"]

# ascii-only: disallow non-ASCII except in configured paths; inline code (backticks) always stripped
# No built-in path/emoji defaults. Options:
# - allowedPathPatternsUnicode: glob list; files where any non-ASCII is allowed
# - allowedPathPatternsEmoji: glob list; files where only allowedEmoji chars are allowed
# - allowedEmoji: emoji/chars allowed in paths matching allowedPathPatternsEmoji (multi-codepoint OK)
# - allowedUnicode: chars allowed in all files; extends default set (é, ï, ñ, ç, etc.) unless replace below
# - allowedUnicodeReplaceDefault: true = use only allowedUnicode list (no default set)
# - allowUnicodeInCodeBlocks: true (default) = skip fenced blocks; false = check them for unicode
# - disallowUnicodeInCodeBlockTypes: when allowUnicodeInCodeBlocks false, only these block types checked
#   (block type = first word after opening fence, e.g. "text" from ```text); empty = check all blocks
# - unicodeReplacements: object or [char, replacement] array; built-in defaults (arrows, quotes, <=>=*) if omitted
ascii-only:
  allowedPathPatternsUnicode:
    # - "**/README.md"
  allowedPathPatternsEmoji:
    - "markdownlint-rules/README.md"
  # allowedUnicode:
  #   - "ń"   # additions on top of default (fixtures e.g. positive_general.md)
  # allowedUnicodeReplaceDefault: false  # true = use only allowedUnicode list, no default set
  allowedEmoji:
    - "✅"
    - "❌"
    - "📊"
    - "⚠️"

# document-length: disallow documents longer than maximum lines (default 1500)
# - maximum: positive integer; default 1500
document-length:
  maximum: 1500

# heading-title-case: AP-style headline capitalization; words in backticks ignored
# heading-title-case:
#   lowercaseWords: ["through", ...]  # optional; extends default list (add words)
#   lowercaseWordsReplaceDefault: true  # optional; true = use only lowercaseWords list, no default set

# no-h1-content: under first h1 allow only TOC (blank, list-of-links, HTML comments)
# - excludePathPatterns: glob list; skip this rule for matching paths (e.g. md_test_files for fixtures)
# no-h1-content:
#   excludePathPatterns:
#     - "README.md"
#     - "CONTRIBUTING.md"
#     - "**/README.md"

# no-empty-heading: H2+ must have content; allow file-level override or per-section suppress comment
# - excludePathPatterns: glob list; skip this rule for matching paths (e.g. **/*_index.md)
# - Other HTML comments in a section are allowed. Only the exact comment
#   "<!-- no-empty-heading allow -->" on its own line (and nothing else) suppresses the error.
no-empty-heading:
  excludePathPatterns:
    - "**/*_index.md"

# allow-custom-anchors: require anchor ids to match patterns; optional placement (line/heading) per pattern
# - allowedIdPatterns: list of regex strings or { pattern, placement? }; placement applies per pattern
# - strictPlacement: true (default) = enforce placement when a pattern has placement set
allow-custom-anchors:
  allowedIdPatterns:
    - pattern: "^spec-[a-z0-9-]+$"
      placement:
        lineMatch: '^- Spec ID:\s+`NP\.[^`]+`'
        anchorImmediatelyAfterHeading: true
    - pattern: "^ref-[a-z0-9]+-[a-z0-9-]+$"
      placement:
        standaloneLine: true
        requireAfter:
          - blank
          - fencedBlock
    - pattern: "^algo-[a-z0-9-]+-step-[0-9]+(?:-[0-9]+)*$"
      placement:
        headingMatch: '^#{1,6} .*`[^`]+`.*\bAlgorithm\b'
        lineMatch: '^\s*(?:[-*+]\s+|\d+[.)]\s+)'
    - pattern: '^algo-[a-z0-9-]+$'
      placement:
        headingMatch: '^\s*#{1,6}\s+.*`[^`]+`.*\bAlgorithm\b'
        standaloneLine: true
        requireAfter:
          - blank
          - list
        anchorImmediatelyAfterHeading: true
        maxPerSection: 1
  strictPlacement: true
...
